### ISSUE TITLE
Doesn't work when installed from npm via tns plugin add

### ISSUE THREAD

**Issue by ventsislav-georgiev** [testfairy/nativescript-testfairy#1]
The package that is published to npm does not contain any .js files. Probably there is an issue with the typescript compilation during packing for publishing.

**Comment by vijaysharm** [comment]
Hi @ventsislav-georgiev,

Thanks for noticing this. With 1.2.0 we moved to an automated build, and clearly forgot to compile the typescript files. I will fix this, and release 1.3.0 later today.

**Comment by vijaysharm** [comment]
Hi,

On further investigation, this appears to be the correct behavior. The previous version erroneously added the compiled javascript files. From what I can tell, nativescript compiles plugins before adding them. You can see this as part of the demo project. I've even confirm this with other plugins in the marketplace. Can you investigate why your nativescript environment is not compiling the plugin?

**Comment by ventsislav-georgiev** [comment]
I do not use typescript and don't have it installed, maybe the plugins are compiled before adding only if typescript is used in the project.

**Comment by vijaysharm** [comment]
From my understanding, you can develop using either javascript or nativescript, however it is `tns` that should compile the files. Perhaps having a look at [this article](https://developer.telerik.com/featured/creating-nativescript-plugins-in-typescript/) from the developer might help?  It appears that all you need to do is include the files as part of your config, and include tsc as part of your build steps.

**Comment by ventsislav-georgiev** [comment]
The referred article is about creating nativescript-plugins and not nativescript apps. Also, in the chapter **Showtime. Let’s Publish** it is specifically listed that the plugin should compile the .ts files before publishing and include the .js files in the package:
* We are not ignoring .js files here.
* ...we will want to make sure that the latest changes are actually built out to .js files before we publish.

**Comment by vijaysharm** [comment]
Interesting! In any case, its not a big deal to add the js to the published library. I've released 1.3.1 which should include the javascript files. Any chance you can give it a try and let me know if the files are included?

**Comment by ventsislav-georgiev** [comment]
Thanks @vijaysharm. I confirm that **v1.3.1** contains the .js files and works for me.
