### ISSUE TITLE
1.4.1 does not appear in npm or Naitvescript Plugin repo 

### ISSUE THREAD

**Issue by mgatto** [testfairy/nativescript-testfairy#2]
Hello,

v1.3.1 is the latest which installs via tns or npm, however Git shows 1.4.1 was released afterwards. Please deploy to the npm and tns repos.

Thanks!

**Comment by vijaysharm** [comment]
Thanks @mgatto! It should be updated now. Looks like our build system failed to report the failed deployment! time for a new cron 💃
